name: Nano Energy Benchmark
description: Nano with xterm-ubuntu terminal emulator via X11/X11-Wayland-Bridge
author: Arne Tarara <arne@green-coding.io>

services:
  xterm-ubuntu:
#    image: ubuntu@sha256:955364933d0d91afa6e10fb045948c16d2b191114aa54bed3ab5430d8bbc58cc # 24.04 as of 04.01.2026
    build: .
    environment:
      - "DISPLAY=:0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./config.js:/tmp/config.js:ro
#    setup-commands:
#      - command: apt update
#      - command: apt install -y xterm
    command: ['tail', '-f', '/dev/null']

flow:
  - name: Start xterm and tmux
    container: xterm-ubuntu
    hidden: true
    commands:
      - type: console
        command: xterm -geometry 160x45 -e "tmux new-session -A -s mysession" # 160x45 corresponds roughly to 1280x720
        detach: true

  - name: Start nano empty
    container: xterm-ubuntu
    commands:
      - type: console
        command: tmux send-keys -t mysession "nano" Enter

  - name: Idle for 10 seconds with empty file
    container: xterm-ubuntu
    commands:
      - type: console
        command: sleep 1000000

  - name: Input a whole source code file
    container: xterm-ubuntu
    commands:
      - type: console
        command: |
          pv -q -L $((1000/80)) /tmp/config.js | while IFS= read -r -n1 char; do
            case "$char" in
              $'\n') char="Enter" ;;
              $'\t') char="Tab" ;;
              $'\b') char="Backspace" ;;
            esac
            tmux send-keys -t mysession "$char"
          done
        shell: bash
