---
name: chrome
author: Didi Hoffmann
description: This is the green code label benchmark script


label:
  - open_source: false
  - no_advertisement: true
  - free_updates: true
  - documentation_link: http://docs.green-coding.io
  - website_link: http://www.green-coding.io
  - sub_packages:
  - file_formats:
    - text/pdf
  - accessibility: true
  - architectures:
    - x86
    - arm64


services:
  bench-service:
    image: ubuntu:24.04
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: ":0"
      LIBGL_ALWAYS_SOFTWARE: 1
      MESA_GL_VERSION_OVERRIDE: 3.3
      QT_XCB_GL_INTEGRATION: none
    docker-run-args:
      - --shm-size=4gb
    setup-commands:
      - echo "tzdata tzdata/Areas select Europe" | debconf-set-selections
      - echo "tzdata tzdata/Zones/Europe select Berlin" | debconf-set-selections
      - echo 'Acquire::http::Proxy "http://192.168.1.17:3142";' >> /etc/apt/apt.conf.d/01proxy
      - echo 'Acquire::HTTPS::Proxy "false";' >> /etc/apt/apt.conf.d/01proxy
      - apt update
      - apt install -y xxd
      - apt install -y dbus dbus-x11
      - mkdir -p /run/dbus
      - dbus-daemon --system --fork
      - head -c 16 /dev/urandom | xxd -p > /etc/machine-id
    networks:
      - benchmark
    shell: /bin/bash


  speedometer:
    build: .
    container_name: speedometer
    ports:
      - "8080:8080"
    networks:
      - benchmark

flow:
  - name: install
    container: bench-service
    commands:
      - type: console
        command: apt install -y konqueror


  - name: idle
    container: bench-service
    commands:
      - type: console
        command: runuser -u ubuntu -- bash -c 'konqueror & sleep 10; pkill -9 -u ubuntu konqueror'
        ignore-errors: True


  - name: run
    container: bench-service
    commands:
      - type: console
        command: runuser -u ubuntu -- bash -c 'konqueror http://speedometer:8080?startAutomatically=true & sleep 30; pkill -9 -u ubuntu konqueror'
        ignore-errors: True


  - name: uninstall
    container: bench-service
    commands:
      - type: console
        command: apt purge --auto-remove -y konqueror

networks:
  benchmark:

